### ISSUE TITLE
Can we use this package for hosting on shared hosting server?

### ISSUE THREAD

**Issue by pushpak1300** [dipeshsukhia/laravel-remove-public-url#2]
While going from repository i didn't understand what does this package do.can we use when we want to host on shared hosting?

**Comment by dipeshsukhia** [comment]
Yes you can.you need to follow steps as described.

**Comment by dipeshsukhia** [comment]
In shared server sometimes we have no access to point public directory. So
in that case you use this package for remove public directory from your app
url.
